/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author albam
 */
public class GameInformationView_Old extends javax.swing.JFrame {

    /**
     * Creates new form GameInformationView
     */
    public GameInformationView_Old() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReturn = new javax.swing.JButton();
        jLabelUsernameFO = new javax.swing.JLabel();
        jLabelName = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jLabelEmailFO = new javax.swing.JLabel();
        jLabelGenre = new javax.swing.JLabel();
        jLabelDescription = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabelStorage = new javax.swing.JLabel();
        jLabelPlatform = new javax.swing.JLabel();
        jLabelSaga = new javax.swing.JLabel();
        jLabelLaunchDate = new javax.swing.JLabel();
        jButtonSeeReviews = new javax.swing.JButton();
        jButtonAddToCart = new javax.swing.JButton();
        jLabelName1 = new javax.swing.JLabel();
        jLabelGenre1 = new javax.swing.JLabel();
        jLabelDescription1 = new javax.swing.JLabel();
        jLabelPrice1 = new javax.swing.JLabel();
        jLabelStorage1 = new javax.swing.JLabel();
        jLabelPlatform1 = new javax.swing.JLabel();
        jLabelSaga1 = new javax.swing.JLabel();
        jLabelLaunchDate1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonReturn.setText("Return");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jLabelUsernameFO.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelUsernameFO.setText("Username");

        jLabelName.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelName.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Game Information");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelEmailFO.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jLabelEmailFO.setText("Email");

        jLabelGenre.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelGenre.setText("Genre:");

        jLabelDescription.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelDescription.setText("Description:");

        jLabelPrice.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice.setText("Price:");

        jLabelStorage.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelStorage.setText("Storage:");

        jLabelPlatform.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPlatform.setText("Platform:");

        jLabelSaga.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelSaga.setText("Saga:");

        jLabelLaunchDate.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelLaunchDate.setText("Launch Date:");

        jButtonSeeReviews.setText("See Game Reviews");
        jButtonSeeReviews.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSeeReviewsActionPerformed(evt);
            }
        });

        jButtonAddToCart.setText("Add to Cart");
        jButtonAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddToCartActionPerformed(evt);
            }
        });

        jLabelName1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelGenre1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelDescription1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelPrice1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelStorage1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelPlatform1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelSaga1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        jLabelLaunchDate1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReturn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonExit)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(0, 199, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmailFO)
                                    .addComponent(jLabelUsernameFO)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelDescription)
                                    .addComponent(jLabelGenre)
                                    .addComponent(jLabelPrice)
                                    .addComponent(jLabelStorage)
                                    .addComponent(jLabelPlatform)
                                    .addComponent(jLabelSaga)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelLaunchDate))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(2, 2, 2)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabelStorage1)
                                                    .addComponent(jLabelPrice1)
                                                    .addComponent(jLabelGenre1)
                                                    .addComponent(jLabelDescription1)
                                                    .addComponent(jLabelName1)))
                                            .addComponent(jLabelSaga1)
                                            .addComponent(jLabelPlatform1))
                                        .addGap(1, 1, 1))
                                    .addComponent(jLabelLaunchDate1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonSeeReviews, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(37, 37, 37))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAddToCart)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUsernameFO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmailFO))
                    .addComponent(jLabel1))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jButtonSeeReviews)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelName)
                            .addComponent(jLabelName1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelGenre)
                            .addComponent(jLabelGenre1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelDescription)
                            .addComponent(jLabelDescription1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPrice)
                            .addComponent(jLabelPrice1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStorage)
                            .addComponent(jLabelStorage1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPlatform)
                            .addComponent(jLabelPlatform1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelSaga)
                            .addComponent(jLabelSaga1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelLaunchDate)
                            .addComponent(jLabelLaunchDate1))
                        .addGap(33, 33, 33)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonReturn)
                    .addComponent(jButtonAddToCart))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonSeeReviewsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSeeReviewsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSeeReviewsActionPerformed

    private void jButtonAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddToCartActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonAddToCartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInformationView_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInformationView_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInformationView_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInformationView_Old.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInformationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonAddToCart;
    public javax.swing.JButton jButtonExit;
    public javax.swing.JButton jButtonReturn;
    public javax.swing.JButton jButtonSeeReviews;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelDescription;
    public javax.swing.JLabel jLabelDescription1;
    public javax.swing.JLabel jLabelEmailFO;
    public javax.swing.JLabel jLabelGenre;
    public javax.swing.JLabel jLabelGenre1;
    public javax.swing.JLabel jLabelLaunchDate;
    public javax.swing.JLabel jLabelLaunchDate1;
    public javax.swing.JLabel jLabelName;
    public javax.swing.JLabel jLabelName1;
    public javax.swing.JLabel jLabelPlatform;
    public javax.swing.JLabel jLabelPlatform1;
    public javax.swing.JLabel jLabelPrice;
    public javax.swing.JLabel jLabelPrice1;
    public javax.swing.JLabel jLabelSaga;
    public javax.swing.JLabel jLabelSaga1;
    public javax.swing.JLabel jLabelStorage;
    public javax.swing.JLabel jLabelStorage1;
    public javax.swing.JLabel jLabelUsernameFO;
    // End of variables declaration//GEN-END:variables
}
