package view;

/**
 *
 * @author Alberto Fernández Merchán
 */
public class MainWindow extends javax.swing.JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        MembersTabMenu = new javax.swing.JMenu();
        MembersManagementItem = new javax.swing.JMenuItem();
        ActivitiesTabMenu = new javax.swing.JMenu();
        ActivityManagementItem = new javax.swing.JMenuItem();
        TrainersTabMenu = new javax.swing.JMenu();
        TrainersManagementItem = new javax.swing.JMenuItem();
        ExitTabMenu = new javax.swing.JMenu();
        ExitExitItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Main Window");

        MembersTabMenu.setText("Members");

        MembersManagementItem.setText("Members Management");
        MembersManagementItem.setActionCommand("MembersManagement");
        MembersManagementItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MembersManagementItemActionPerformed(evt);
            }
        });
        MembersTabMenu.add(MembersManagementItem);

        jMenuBar1.add(MembersTabMenu);

        ActivitiesTabMenu.setText("Activities");

        ActivityManagementItem.setText("Activities Management");
        ActivitiesTabMenu.add(ActivityManagementItem);

        jMenuBar1.add(ActivitiesTabMenu);

        TrainersTabMenu.setText("Trainers");

        TrainersManagementItem.setText("Trainers Management");
        TrainersTabMenu.add(TrainersManagementItem);

        jMenuBar1.add(TrainersTabMenu);

        ExitTabMenu.setText("Exit");
        ExitTabMenu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitTabMenuMouseClicked(evt);
            }
        });

        ExitExitItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F12, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        ExitExitItem.setText("Exit");
        ExitExitItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitExitItemActionPerformed(evt);
            }
        });
        ExitTabMenu.add(ExitExitItem);

        jMenuBar1.add(ExitTabMenu);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1301, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitTabMenuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitTabMenuMouseClicked

    }//GEN-LAST:event_ExitTabMenuMouseClicked

    private void MembersManagementItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MembersManagementItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MembersManagementItemActionPerformed

    private void ExitExitItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitExitItemActionPerformed
        System.exit(0);
    }//GEN-LAST:event_ExitExitItemActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainWindow().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu ActivitiesTabMenu;
    public javax.swing.JMenuItem ActivityManagementItem;
    private javax.swing.JMenuItem ExitExitItem;
    private javax.swing.JMenu ExitTabMenu;
    public javax.swing.JMenuItem MembersManagementItem;
    private javax.swing.JMenu MembersTabMenu;
    public javax.swing.JMenuItem TrainersManagementItem;
    public javax.swing.JMenu TrainersTabMenu;
    private javax.swing.JMenuBar jMenuBar1;
    // End of variables declaration//GEN-END:variables
}
