/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author albam
 */
public class AddPaymentMethodView extends javax.swing.JFrame {

    /**
     * Creates new form AddPaymentMethodView
     */
    public AddPaymentMethodView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonExitFromRegister = new javax.swing.JButton();
        jButtomRegisterFromRegister = new javax.swing.JButton();
        jLabelRegister = new javax.swing.JLabel();
        jTextFieldPostalCode = new javax.swing.JTextField();
        jTextFieldStateProvince = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldAddressLine2 = new javax.swing.JTextField();
        jLabelStateProvince = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelAddressLine3 = new javax.swing.JLabel();
        jLabelAddressLine1 = new javax.swing.JLabel();
        jTextFieldAddressLine1 = new javax.swing.JTextField();
        jLabelPostalCode = new javax.swing.JLabel();
        jLabelTitle2 = new javax.swing.JLabel();
        jLabelTitle3 = new javax.swing.JLabel();
        jLabelAddressLine2 = new javax.swing.JLabel();
        jLabelAddressLine4 = new javax.swing.JLabel();
        jLabelStateProvince1 = new javax.swing.JLabel();
        jTextFieldAddressLine3 = new javax.swing.JTextField();
        jTextFieldCity1 = new javax.swing.JTextField();
        jTextFieldStateProvince1 = new javax.swing.JTextField();
        jTextFieldAddressLine4 = new javax.swing.JTextField();
        jLabelAddressLine5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonExitFromRegister.setText("Exit");

        jButtomRegisterFromRegister.setText("Confirm");
        jButtomRegisterFromRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtomRegisterFromRegisterActionPerformed(evt);
            }
        });

        jLabelRegister.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelRegister.setText("Add Payment Method");

        jTextFieldPostalCode.setText("Postal Code");
        jTextFieldPostalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPostalCodeActionPerformed(evt);
            }
        });

        jTextFieldStateProvince.setText("StateProvince");
        jTextFieldStateProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStateProvinceActionPerformed(evt);
            }
        });

        jTextFieldCity.setText("City");
        jTextFieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCityActionPerformed(evt);
            }
        });

        jTextFieldAddressLine2.setText("Address Line 2");
        jTextFieldAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine2ActionPerformed(evt);
            }
        });

        jLabelStateProvince.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelStateProvince.setText("StateProvince");

        jLabelCity.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelCity.setText("City");

        jLabelAddressLine3.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine3.setText("Address Line 2");

        jLabelAddressLine1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine1.setText("Address Line 1");

        jTextFieldAddressLine1.setText("Address Line 1");
        jTextFieldAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine1ActionPerformed(evt);
            }
        });

        jLabelPostalCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelPostalCode.setText("PostalCode");

        jLabelTitle2.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTitle2.setText("Billing Address");

        jLabelTitle3.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelTitle3.setText("Card");

        jLabelAddressLine2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine2.setText("Card Number");

        jLabelAddressLine4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine4.setText("Month Exp");

        jLabelStateProvince1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelStateProvince1.setText("CVV");

        jTextFieldAddressLine3.setText("MM");
        jTextFieldAddressLine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine3ActionPerformed(evt);
            }
        });

        jTextFieldCity1.setText("YY");
        jTextFieldCity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCity1ActionPerformed(evt);
            }
        });

        jTextFieldStateProvince1.setText("CVV");
        jTextFieldStateProvince1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStateProvince1ActionPerformed(evt);
            }
        });

        jTextFieldAddressLine4.setText("Card Number");
        jTextFieldAddressLine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine4ActionPerformed(evt);
            }
        });

        jLabelAddressLine5.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine5.setText("Year Exp");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtomRegisterFromRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonExitFromRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(183, 183, 183)
                        .addComponent(jLabelRegister)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelAddressLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAddressLine3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelCity, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelStateProvince, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelPostalCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldAddressLine1)
                    .addComponent(jTextFieldAddressLine2)
                    .addComponent(jTextFieldCity)
                    .addComponent(jTextFieldStateProvince, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldPostalCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabelAddressLine2, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                    .addComponent(jLabelAddressLine4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelStateProvince1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabelAddressLine5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextFieldCity1, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAddressLine3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextFieldAddressLine4, javax.swing.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
                    .addComponent(jTextFieldStateProvince1))
                .addContainerGap(15, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jLabelTitle2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabelTitle3)
                .addGap(113, 113, 113))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabelRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle2)
                    .addComponent(jLabelTitle3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddressLine1)
                            .addComponent(jTextFieldAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelAddressLine3)
                            .addComponent(jTextFieldAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelCity)
                            .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelStateProvince)
                            .addComponent(jTextFieldStateProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelPostalCode)
                            .addComponent(jTextFieldPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAddressLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddressLine2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddressLine4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelAddressLine5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextFieldStateProvince1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelStateProvince1))))
                .addGap(62, 62, 62)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExitFromRegister)
                    .addComponent(jButtomRegisterFromRegister))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtomRegisterFromRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtomRegisterFromRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtomRegisterFromRegisterActionPerformed

    private void jTextFieldPostalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPostalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPostalCodeActionPerformed

    private void jTextFieldStateProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStateProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStateProvinceActionPerformed

    private void jTextFieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCityActionPerformed

    private void jTextFieldAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine2ActionPerformed

    private void jTextFieldAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine1ActionPerformed

    private void jTextFieldAddressLine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine3ActionPerformed

    private void jTextFieldCity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCity1ActionPerformed

    private void jTextFieldStateProvince1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStateProvince1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStateProvince1ActionPerformed

    private void jTextFieldAddressLine4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddPaymentMethodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddPaymentMethodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddPaymentMethodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddPaymentMethodView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddPaymentMethodView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtomRegisterFromRegister;
    private javax.swing.JButton jButtonExitFromRegister;
    public javax.swing.JLabel jLabelAddressLine1;
    public javax.swing.JLabel jLabelAddressLine2;
    public javax.swing.JLabel jLabelAddressLine3;
    public javax.swing.JLabel jLabelAddressLine4;
    public javax.swing.JLabel jLabelAddressLine5;
    public javax.swing.JLabel jLabelCity;
    public javax.swing.JLabel jLabelPostalCode;
    public javax.swing.JLabel jLabelRegister;
    public javax.swing.JLabel jLabelStateProvince;
    public javax.swing.JLabel jLabelStateProvince1;
    public javax.swing.JLabel jLabelTitle2;
    public javax.swing.JLabel jLabelTitle3;
    public javax.swing.JTextField jTextFieldAddressLine1;
    public javax.swing.JTextField jTextFieldAddressLine2;
    public javax.swing.JTextField jTextFieldAddressLine3;
    public javax.swing.JTextField jTextFieldAddressLine4;
    public javax.swing.JTextField jTextFieldCity;
    public javax.swing.JTextField jTextFieldCity1;
    public javax.swing.JTextField jTextFieldPostalCode;
    public javax.swing.JTextField jTextFieldStateProvince;
    public javax.swing.JTextField jTextFieldStateProvince1;
    // End of variables declaration//GEN-END:variables
}
