/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author albam
 */
public class GameInformationView extends javax.swing.JFrame {

    /**
     * Creates new form GameInformationView
     */
    public GameInformationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextGameName = new javax.swing.JTextField();
        jButtonSearch = new javax.swing.JButton();
        jButtonReturn = new javax.swing.JButton();
        jLabelUsernameFO = new javax.swing.JLabel();
        jLabelPrice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jLabelEmailFO = new javax.swing.JLabel();
        jLabelPrice1 = new javax.swing.JLabel();
        jLabelPrice2 = new javax.swing.JLabel();
        jLabelPrice3 = new javax.swing.JLabel();
        jLabelPrice4 = new javax.swing.JLabel();
        jLabelPrice5 = new javax.swing.JLabel();
        jLabelPrice6 = new javax.swing.JLabel();
        jLabelPrice7 = new javax.swing.JLabel();
        jButtonReturn1 = new javax.swing.JButton();
        jButtonReturn2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTextGameName.setText("Game Name");
        jTextGameName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextGameNameActionPerformed(evt);
            }
        });

        jButtonSearch.setText("Search");
        jButtonSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSearchActionPerformed(evt);
            }
        });

        jButtonReturn.setText("Return");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jLabelUsernameFO.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabelUsernameFO.setText("Username");

        jLabelPrice.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice.setText("Name:");

        jLabel1.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel1.setText("Game Information");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelEmailFO.setFont(new java.awt.Font("Calibri", 0, 10)); // NOI18N
        jLabelEmailFO.setText("Email");

        jLabelPrice1.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice1.setText("Genre:");

        jLabelPrice2.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice2.setText("Description:");

        jLabelPrice3.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice3.setText("Price:");

        jLabelPrice4.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice4.setText("Storage:");

        jLabelPrice5.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice5.setText("Platform:");

        jLabelPrice6.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice6.setText("Saga:");

        jLabelPrice7.setFont(new java.awt.Font("Calibri", 0, 12)); // NOI18N
        jLabelPrice7.setText("Launch Date:");

        jButtonReturn1.setText("See Game Reviews");
        jButtonReturn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturn1ActionPerformed(evt);
            }
        });

        jButtonReturn2.setText("Add to Cart");
        jButtonReturn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturn2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButtonReturn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonExit)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonReturn1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(81, 81, 81)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelEmailFO)
                                    .addComponent(jLabelUsernameFO))))
                        .addGap(37, 37, 37))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jTextGameName, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelPrice1)
                            .addComponent(jLabelPrice)
                            .addComponent(jLabelPrice2)
                            .addComponent(jLabelPrice4)
                            .addComponent(jLabelPrice5)
                            .addComponent(jLabelPrice6)
                            .addComponent(jLabelPrice7)
                            .addComponent(jLabelPrice3)
                            .addComponent(jButtonReturn2))))
                .addContainerGap(173, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelUsernameFO)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabelEmailFO))
                    .addComponent(jLabel1))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSearch)
                    .addComponent(jTextGameName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addComponent(jLabelPrice)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrice1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPrice2)
                    .addComponent(jButtonReturn1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrice3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrice4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrice5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrice6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelPrice7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonReturn)
                    .addComponent(jButtonReturn2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonSearchActionPerformed

    private void jTextGameNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextGameNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextGameNameActionPerformed

    private void jButtonReturn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturn1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReturn1ActionPerformed

    private void jButtonReturn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturn2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReturn2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameInformationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonExit;
    public javax.swing.JButton jButtonReturn;
    public javax.swing.JButton jButtonReturn1;
    public javax.swing.JButton jButtonReturn2;
    public javax.swing.JButton jButtonSearch;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabelEmailFO;
    public javax.swing.JLabel jLabelPrice;
    public javax.swing.JLabel jLabelPrice1;
    public javax.swing.JLabel jLabelPrice2;
    public javax.swing.JLabel jLabelPrice3;
    public javax.swing.JLabel jLabelPrice4;
    public javax.swing.JLabel jLabelPrice5;
    public javax.swing.JLabel jLabelPrice6;
    public javax.swing.JLabel jLabelPrice7;
    public javax.swing.JLabel jLabelUsernameFO;
    public javax.swing.JTextField jTextGameName;
    // End of variables declaration//GEN-END:variables
}
