/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author albam
 */
public class RegisterView extends javax.swing.JFrame {

    /**
     * Creates new form RegisterView
     */
    public RegisterView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTitle = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelMiddleName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonExitFromRegister = new javax.swing.JButton();
        jLabelTitle1 = new javax.swing.JLabel();
        jLabelAddressLine1 = new javax.swing.JLabel();
        jLabelAddressLine2 = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelStateProvince = new javax.swing.JLabel();
        jLabelPostalCode = new javax.swing.JLabel();
        jComboBoxAdressType = new javax.swing.JComboBox<>();
        jTextFieldAddressLine1 = new javax.swing.JTextField();
        jTextFieldAddressLine2 = new javax.swing.JTextField();
        jTextFieldCity = new javax.swing.JTextField();
        jTextFieldStateProvince = new javax.swing.JTextField();
        jTextFieldPostalCode = new javax.swing.JTextField();
        jComboBoxTitle = new javax.swing.JComboBox<>();
        jButtomRegisterFromRegister = new javax.swing.JButton();
        jTextFieldAddressLine3 = new javax.swing.JTextField();
        jLabelRegister = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jTextFieldAddressLine4 = new javax.swing.JTextField();
        jTextFieldAddressLine5 = new javax.swing.JTextField();
        jTextFieldAddressLine6 = new javax.swing.JTextField();
        jTextFieldAddressLine7 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabelTitle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelTitle.setText("Title");

        jLabelFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelFirstName.setText("FirstName");

        jLabelMiddleName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelMiddleName.setText("MiddleName");

        jLabelLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelLastName.setText("LastName");

        jLabelEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelEmail.setText("EmailAddress");

        jLabelPhoneNumber.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelPhoneNumber.setText("Phone Number");

        jLabelPassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelPassword.setText("Password");

        jButtonExitFromRegister.setText("Exit");

        jLabelTitle1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelTitle1.setText("Address Type");

        jLabelAddressLine1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine1.setText("Address Line 1");

        jLabelAddressLine2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine2.setText("Address Line 2");

        jLabelCity.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelCity.setText("City");

        jLabelStateProvince.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelStateProvince.setText("StateProvince");

        jLabelPostalCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelPostalCode.setText("PostalCode");

        jComboBoxAdressType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Home", "Main Office" }));
        jComboBoxAdressType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAdressTypeActionPerformed(evt);
            }
        });

        jTextFieldAddressLine1.setText("Address Line 1");
        jTextFieldAddressLine1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine1ActionPerformed(evt);
            }
        });

        jTextFieldAddressLine2.setText("Address Line 2");
        jTextFieldAddressLine2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine2ActionPerformed(evt);
            }
        });

        jTextFieldCity.setText("City");
        jTextFieldCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCityActionPerformed(evt);
            }
        });

        jTextFieldStateProvince.setText("StateProvince");
        jTextFieldStateProvince.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldStateProvinceActionPerformed(evt);
            }
        });

        jTextFieldPostalCode.setText("Postal Code");
        jTextFieldPostalCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldPostalCodeActionPerformed(evt);
            }
        });

        jComboBoxTitle.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mr.", "Mrs.", "Ms.", "Sr.", "Sra." }));
        jComboBoxTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTitleActionPerformed(evt);
            }
        });

        jButtomRegisterFromRegister.setText("Register");
        jButtomRegisterFromRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtomRegisterFromRegisterActionPerformed(evt);
            }
        });

        jTextFieldAddressLine3.setText("FirstName");
        jTextFieldAddressLine3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine3ActionPerformed(evt);
            }
        });

        jLabelRegister.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelRegister.setText("Register");

        jPasswordField1.setText("jPasswordField1");
        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });

        jTextFieldAddressLine4.setText("MiddleName");
        jTextFieldAddressLine4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine4ActionPerformed(evt);
            }
        });

        jTextFieldAddressLine5.setText("LastName");
        jTextFieldAddressLine5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine5ActionPerformed(evt);
            }
        });

        jTextFieldAddressLine6.setText("Email");
        jTextFieldAddressLine6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine6ActionPerformed(evt);
            }
        });

        jTextFieldAddressLine7.setText("Phone");
        jTextFieldAddressLine7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldAddressLine7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 249, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jButtomRegisterFromRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExitFromRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(19, 19, 19))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabelRegister, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(253, 253, 253))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabelAddressLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelAddressLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelCity, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelStateProvince, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabelPostalCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelTitle1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(39, 39, 39)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAddressLine1)
                            .addComponent(jComboBoxAdressType, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAddressLine2)
                            .addComponent(jTextFieldCity)
                            .addComponent(jTextFieldStateProvince, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldPostalCode, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelMiddleName)
                            .addComponent(jLabelTitle)
                            .addComponent(jLabelPhoneNumber)
                            .addComponent(jLabelEmail)
                            .addComponent(jLabelLastName)
                            .addComponent(jLabelFirstName)
                            .addComponent(jLabelPassword))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFieldAddressLine4)
                            .addComponent(jTextFieldAddressLine3)
                            .addComponent(jComboBoxTitle, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jTextFieldAddressLine5)
                            .addComponent(jTextFieldAddressLine6, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextFieldAddressLine7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 119, Short.MAX_VALUE)
                            .addComponent(jPasswordField1, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabelRegister)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelTitle1)
                    .addComponent(jComboBoxAdressType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBoxTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName)
                    .addComponent(jLabelAddressLine1)
                    .addComponent(jTextFieldAddressLine1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddressLine3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMiddleName)
                    .addComponent(jLabelAddressLine2)
                    .addComponent(jTextFieldAddressLine2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddressLine4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName)
                    .addComponent(jLabelCity)
                    .addComponent(jTextFieldCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddressLine5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelStateProvince)
                    .addComponent(jTextFieldStateProvince, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddressLine6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jLabelPostalCode)
                    .addComponent(jTextFieldPostalCode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldAddressLine7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPassword)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExitFromRegister)
                    .addComponent(jButtomRegisterFromRegister))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAdressTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAdressTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAdressTypeActionPerformed

    private void jTextFieldAddressLine1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine1ActionPerformed

    private void jTextFieldAddressLine2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine2ActionPerformed

    private void jTextFieldCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCityActionPerformed

    private void jTextFieldStateProvinceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldStateProvinceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldStateProvinceActionPerformed

    private void jTextFieldPostalCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldPostalCodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldPostalCodeActionPerformed

    private void jComboBoxTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTitleActionPerformed

    private void jButtomRegisterFromRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtomRegisterFromRegisterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtomRegisterFromRegisterActionPerformed

    private void jTextFieldAddressLine3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine3ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void jTextFieldAddressLine4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine4ActionPerformed

    private void jTextFieldAddressLine5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine5ActionPerformed

    private void jTextFieldAddressLine6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine6ActionPerformed

    private void jTextFieldAddressLine7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldAddressLine7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldAddressLine7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtomRegisterFromRegister;
    private javax.swing.JButton jButtonExitFromRegister;
    public javax.swing.JComboBox<String> jComboBoxAdressType;
    public javax.swing.JComboBox<String> jComboBoxTitle;
    public javax.swing.JLabel jLabelAddressLine1;
    public javax.swing.JLabel jLabelAddressLine2;
    public javax.swing.JLabel jLabelCity;
    public javax.swing.JLabel jLabelEmail;
    public javax.swing.JLabel jLabelFirstName;
    public javax.swing.JLabel jLabelLastName;
    public javax.swing.JLabel jLabelMiddleName;
    public javax.swing.JLabel jLabelPassword;
    public javax.swing.JLabel jLabelPhoneNumber;
    public javax.swing.JLabel jLabelPostalCode;
    public javax.swing.JLabel jLabelRegister;
    public javax.swing.JLabel jLabelStateProvince;
    public javax.swing.JLabel jLabelTitle;
    public javax.swing.JLabel jLabelTitle1;
    private javax.swing.JPasswordField jPasswordField1;
    public javax.swing.JTextField jTextFieldAddressLine1;
    public javax.swing.JTextField jTextFieldAddressLine2;
    public javax.swing.JTextField jTextFieldAddressLine3;
    public javax.swing.JTextField jTextFieldAddressLine4;
    public javax.swing.JTextField jTextFieldAddressLine5;
    public javax.swing.JTextField jTextFieldAddressLine6;
    public javax.swing.JTextField jTextFieldAddressLine7;
    public javax.swing.JTextField jTextFieldCity;
    public javax.swing.JTextField jTextFieldPostalCode;
    public javax.swing.JTextField jTextFieldStateProvince;
    // End of variables declaration//GEN-END:variables
}
