/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

/**
 *
 * @author albam
 */
public class PersonalInformationView extends javax.swing.JFrame {

    /**
     * Creates new form PersonalInformationView
     */
    public PersonalInformationView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonReturn = new javax.swing.JButton();
        jLabelTitle = new javax.swing.JLabel();
        jLabelFirstName = new javax.swing.JLabel();
        jLabelRegister = new javax.swing.JLabel();
        jLabelMiddleName = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jLabelEmail = new javax.swing.JLabel();
        jLabelPhoneNumber = new javax.swing.JLabel();
        jLabelPassword = new javax.swing.JLabel();
        jButtonExit = new javax.swing.JButton();
        jLabelAddressType = new javax.swing.JLabel();
        jLabelAddressLine1 = new javax.swing.JLabel();
        jLabelAddressLine2 = new javax.swing.JLabel();
        jLabelCity = new javax.swing.JLabel();
        jLabelStateProvince = new javax.swing.JLabel();
        jLabelPostalCode = new javax.swing.JLabel();
        jButtonEdit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jButtonReturn.setText("Return");
        jButtonReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReturnActionPerformed(evt);
            }
        });

        jLabelTitle.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelTitle.setText("Title");

        jLabelFirstName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelFirstName.setText("FirstName");

        jLabelRegister.setFont(new java.awt.Font("Calibri", 0, 24)); // NOI18N
        jLabelRegister.setText("Personal Information");

        jLabelMiddleName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelMiddleName.setText("MiddleName");

        jLabelLastName.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelLastName.setText("LastName");

        jLabelEmail.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelEmail.setText("EmailAddress");

        jLabelPhoneNumber.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelPhoneNumber.setText("Phone Number");

        jLabelPassword.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelPassword.setText("Password");

        jButtonExit.setText("Exit");
        jButtonExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExitActionPerformed(evt);
            }
        });

        jLabelAddressType.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressType.setText("Address Type");

        jLabelAddressLine1.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine1.setText("Address Line 1");

        jLabelAddressLine2.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelAddressLine2.setText("Address Line 2");

        jLabelCity.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelCity.setText("City");

        jLabelStateProvince.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelStateProvince.setText("StateProvince");

        jLabelPostalCode.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabelPostalCode.setText("PostalCode");

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(163, 163, 163)
                        .addComponent(jLabelRegister)
                        .addGap(27, 27, 27))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabelAddressLine1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelAddressLine2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelCity, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelStateProvince, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabelPostalCode, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabelAddressType, javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabelMiddleName)
                                    .addComponent(jLabelTitle)
                                    .addComponent(jLabelPhoneNumber)
                                    .addComponent(jLabelEmail)
                                    .addComponent(jLabelLastName)
                                    .addComponent(jLabelFirstName)
                                    .addComponent(jLabelPassword))))))
                .addContainerGap(157, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonReturn, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonExit, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(25, Short.MAX_VALUE)
                .addComponent(jLabelRegister)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelAddressType))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelFirstName)
                    .addComponent(jLabelAddressLine1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelMiddleName)
                    .addComponent(jLabelAddressLine2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName)
                    .addComponent(jLabelCity))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEmail)
                    .addComponent(jLabelStateProvince))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelPhoneNumber)
                    .addComponent(jLabelPostalCode))
                .addGap(18, 18, 18)
                .addComponent(jLabelPassword)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonExit)
                    .addComponent(jButtonReturn)
                    .addComponent(jButtonEdit))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonReturnActionPerformed

    private void jButtonExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExitActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonExitActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonEditActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PersonalInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PersonalInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PersonalInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PersonalInformationView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PersonalInformationView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton jButtonEdit;
    public javax.swing.JButton jButtonExit;
    public javax.swing.JButton jButtonReturn;
    public javax.swing.JLabel jLabelAddressLine1;
    public javax.swing.JLabel jLabelAddressLine2;
    public javax.swing.JLabel jLabelAddressType;
    public javax.swing.JLabel jLabelCity;
    public javax.swing.JLabel jLabelEmail;
    public javax.swing.JLabel jLabelFirstName;
    public javax.swing.JLabel jLabelLastName;
    public javax.swing.JLabel jLabelMiddleName;
    public javax.swing.JLabel jLabelPassword;
    public javax.swing.JLabel jLabelPhoneNumber;
    public javax.swing.JLabel jLabelPostalCode;
    public javax.swing.JLabel jLabelRegister;
    public javax.swing.JLabel jLabelStateProvince;
    public javax.swing.JLabel jLabelTitle;
    // End of variables declaration//GEN-END:variables
}
